server:
  port: 8085
spring:
  application:
    name: api-gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: jwt-authenticate-service
  cloud:
    gateway:
      routes:
        - id: rest-server
          uri: http://localhost:9090
          predicates:
            - Path=/rest/**
          filters:
        - RemoveRequestHeader=Cookie
eureka:
  client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
   instance:
     preferIpAddress: false